id: '001'
mission: LID #{LID, ASR, ALL}
task: train  #{train, evaluate, null(if no need to specified)}

LID: 
  runner:
    total_steps: 10000
    gradient_clipping: 1
    gradient_accumulate_steps: 128
    log_step: 5
    eval_step: 50
    save_step: 20
    max_keep: 1
    eval_dataloader: test

  optimizer: 
    name: TorchOptim
    torch_optim_name: Adam
    lr: 6.0e-5
    ckpt: true

  DATASET:
    bucket_path: '/home/b07502072/cs_ssl/iven/hubert_asr/len_for_bucket/SEAME'
    data_path: ''
    load_valid: './data/valid_names/SEAME'
    train: ['train']
    test: ['dev-man', 'dev-sge']

  UPSTREAM: 
    name: wav2vec2_base_960
    ckpt: null

  FEATURIZER:
    type: weighted-sum
    ckpt: true

  SPECAUG:
    apply_time_warp: true
    apply_time_mask: true
    apply_freq_mask: true
    time_warp_window: 5
    time_mask_width_range: [0, 40]
    freq_mask_width_range: [0, 50]
    num_freq_mask: 4
    num_time_mask: 2

  DOWNSTREAM:
    ckpt: true
    model_type: RNNs
    proj_dim: 1024
    RNNs:
      module: LSTM
      bidirection: true
      dim: [1024, 1024]
      dropout: [0.2, 0.2]
      layer_norm: [False, False]
      proj: [False, False]
      output_size: 4
    CNN:

ASR:
  runner:
    total_steps: 10000
    gradient_clipping: 1
    gradient_accumulate_steps: 128
    log_step: 5
    eval_step: 50
    save_step: 20
    max_keep: 1
    eval_dataloader: test

  optimizer: 
    name: TorchOptim
    torch_optim_name: Adam
    lr: 6.0e-5
    ckpt: true

  DATASET:
    bucket_path: '/home/b07502072/cs_ssl/iven/hubert_asr/len_for_bucket/SEAME'
    data_path: ''
    load_valid: './data/valid_names/SEAME'
    train: ['train']
    test: ['dev-man', 'dev-sge']

  UPSTREAM: 
    name: wav2vec2_base_960
    ckpt: null

  FEATURIZER:
    type: weighted-sum
    ckpt: true

  SPECAUG:
    apply_time_warp: true
    apply_time_mask: true
    apply_freq_mask: true
    time_warp_window: 5
    time_mask_width_range: [0, 40]
    freq_mask_width_range: [0, 50]
    num_freq_mask: 4
    num_time_mask: 2

  DOWNSTREAM:
    ckpt: true
    model_type: RNNs
    proj_dim: 1024
    RNNs:
      module: LSTM
      bidirection: true
      dim: [1024, 1024]
      dropout: [0.2, 0.2]
      layer_norm: [False, False]
      proj: [False, False]
    