id: '001'
mission: LID #{LID, ASR}

hyperparams:
  total_steps: 1000000
  gradient_clipping: 1
  gradient_accumulate_steps: 32
  log_step: 10000
  eval_step: 50000
  save_step: 100000
  max_keep: 1
  eval_dataloaders:
    - test

DATASET:
  bucket_path: './data/len_for_bucket/SEAME'
  data_path: './data/SEAME'
  train: ['train']
  test: ['dev-man', 'dev-sge']

UPSTREAM: 
  name: wav2vec2_xlsr
  ckpt: null

FEATURIZER:
  type: weighted-sum
  ckpt: null

SPECAUG:
  apply_time_warp: true
  apply_time_mask: true
  apply_freq_mask: true
  time_warp_window: 5
  time_mask_width_range: [0, 40]
  freq_mask_width_range: [0, 50]
  num_freq_mask: 4
  num_time_mask: 2

DOWNSTREAM:
  ckpt: null
  model_type: RNNs
  proj_dim: 1024
  RNNs:
    input_dim: 1024
    output_dim: 3
    module: LSTM
    bidirection: true
    dim: [1024, 1024]
    dropout: [0.2, 0.2]
    layer_norm: [False, False]
    proj: [False, False]
  CNN:
  
optimizer: 
  name: TorchOptim
  torch_optim_name: Adam
  lr: 6.0e-5