id: "001"
mission: ASR
task: train

load_ckpt: last
runner:
  total_steps: 200000
  gradient_clipping: 1
  gradient_accumulate_steps: 1
  log_step: 200
  eval_step: 5000
  save_step: 100
  max_keep: 1
  eval_dataloader: dev

optimizer: 
  name: TorchOptim
  torch_optim_name: Adam
  lr: 6.0e-5

scheduler:
  name: costum_scheduler
  num_warmup_steps: 10000
  num_decay_steps:  50000

DATASET:
  bucket_size: 32 # -> to be set
  bucket_path: '/home/b07502072/cs_ssl/cs_asr_ssl/data/len_for_bucket/splitted-seame'
  data_path: ''
  dict_path: './dicts/dict_seame.model'
  dict_mode: 'subword'
  train: ['train']
  dev: ['dev']
  test: ['dev-man', 'dev-sge']
  zero_infinity: true

UPSTREAM: 
  name: wav2vec2_base_960

SPECAUG:
  apply_time_warp: true
  apply_time_mask: true
  apply_freq_mask: true
  time_warp_window: 5
  time_mask_width_range: [0, 40]
  freq_mask_width_range: [0, 50]
  num_freq_mask: 4
  num_time_mask: 2
