id: '002'
mission: ASR #{LID, ASR, ALL}
task: train  #{train, evaluate, null(if no need to specified)}

LID: 
  load_ckpt: last
  runner:
    total_steps: 10000
    gradient_clipping: 1
    gradient_accumulate_steps: 128
    log_step: 5
    eval_step: 50
    save_step: 20
    max_keep: 1
    eval_dataloader: test

  optimizer: 
    name: TorchOptim
    torch_optim_name: Adam
    lr: 6.0e-5

  DATASET:
    bucket_path: '/home/b07502072/cs_ssl/iven/hubert_asr/len_for_bucket/SEAME'
    data_path: ''
    load_valid: './data/valid_names/SEAME'
    train: ['train']
    test: ['dev-man', 'dev-sge']

  UPSTREAM: 
    name: wav2vec2_base_960
    ckpt: null

  FEATURIZER:
    type: weighted-sum
    ckpt: true

  SPECAUG:
    apply_time_warp: true
    apply_time_mask: true
    apply_freq_mask: true
    time_warp_window: 5
    time_mask_width_range: [0, 40]
    freq_mask_width_range: [0, 50]
    num_freq_mask: 4
    num_time_mask: 2

  DOWNSTREAM:
    ckpt: true
    model_type: RNNs
    proj_dim: 512
    RNNs:
      module: LSTM
      bidirection: true
      dim: [512, 128]
      dropout: [0.2, 0.1]
      layer_norm: [False, False]
      proj: [False, False]
      output_size: 3
    CNN:

ASR:
  load_ckpt: last
  runner:
    total_steps: 100000
    gradient_clipping: 1
    gradient_accumulate_steps: 1
    log_step: 200
    eval_step: 5000
    save_step: 100
    max_keep: 1
    eval_dataloader: test

  optimizer: 
    name: TorchOptim
    torch_optim_name: Adam
    lr: 1.0e-4

  DATASET:
    bucket_size: 32
    bucket_path: '/home/b07502072/cs_ssl/iven/hubert_asr/len_for_bucket/SEAME'
    data_path: ''
    dict_path: './dicts/dict_10k.model'
    dict_mode: 'subword'
    train: ['train']
    test: ['dev-man', 'dev-sge']
    zero_infinity: true

  UPSTREAM: 
    name: wav2vec2_base_960

  FEATURIZER:
    type: weighted-sum

  SPECAUG:
    apply_time_warp: true
    apply_time_mask: true
    apply_freq_mask: true
    time_warp_window: 5
    time_mask_width_range: [0, 40]
    freq_mask_width_range: [0, 50]
    num_freq_mask: 4
    num_time_mask: 2

  DOWNSTREAM:
    model_type: RNNs
    proj_dim: 1024
    RNNs:
      module: LSTM
      bidirection: true
      dim: [1024, 1024]
      dropout: [0.2, 0.2]
      layer_norm: [False, False]
      proj: [False, False]

ALL:
  load_ckpt: last
  asr_ckpt: /home/b07502072/cs_ssl/cs_asr_ssl/results/wav2vec2_base_960/002/ASR
  lid_ckpt: /home/b07502072/cs_ssl/cs_asr_ssl/results/wav2vec2_base_960/001/LID