id: '301'
mission: IVEN #{LID, ASR, ALL}
task: draw_iven_ctc #{train, evaluate, null(if no need to specified)}
device_idx: 0

ASR:
  load_ckpt: /home/b07502072/cs_ssl/model/lid_base.ckpt
  runner:
    total_steps: 200000
    gradient_clipping: 1
    gradient_accumulate_steps: 1
    log_step: 200
    eval_step: 2500
    save_step: 500
    max_keep: 1
    eval_dataloader: dev

  optimizer: 
    name: TorchOptim
    torch_optim_name: Adam
    lr: 6.0e-5

  scheduler:
    name: costum_scheduler
    num_warmup_steps: 10000
    num_decay_steps: 50000

  DATASET:
    bucket_size: 32
    bucket_path: '/home/b07502072/cs_ssl/cs_asr_ssl/data/len_for_bucket/splitted-seame'
    data_path: ''
    load_valid: './data/valid_names/splitted-seame'
    dict_path: './dicts/dict_seame.model'
    dict_mode: 'subword'
    train: ['train']
    dev: ['dev']
    test: ['dev-man']
    zero_infinity: true

  UPSTREAM: 
    name: wav2vec2_base_960

  FEATURIZER:
    type: weighted-sum
    layer-norm: true

  SPECAUG:
    apply_time_warp: true
    apply_time_mask: true
    apply_freq_mask: true
    time_warp_window: 5
    time_mask_width_range: [0, 40]
    freq_mask_width_range: [0, 50]
    num_freq_mask: 4
    num_time_mask: 2

  DOWNSTREAM:
    model_type: Iven_RNNs
    proj_dim: 1024
    Iven_RNNs:
      module: LSTM
      bidirection: true
      lid_output_size: 4
      dim: [1024, 1024]
      dropout: [0.2, 0.2]
      layer_norm: [False, False]
      proj: [False, False]

      # input_size,
      # output_size,
      # lid_output_size,
      # module,
      # bidirection,
      # dim,
      # dropout,
      # layer_norm
ALL:
  asr_ckpt: /home/b07502072/cs_ssl/cs_asr_ssl/results/wav2vec2_base_960/002/ASR/states-96100.ckpt
  lid_ckpt: /home/b07502072/cs_ssl/cs_asr_ssl/results/wav2vec2_base_960/001/LID/states-940.ckpt